#! /bin/bash

usage() {
    cat << EOF
Usage: shutdown [OPTION]
 -r, -R, --reboot      Reboot
 -p, -P, --poweroff    Poweroff
EOF
    exit 0
}

scandir=$(head -n1 /etc/s6-linux-init/env/DEST)

signal="${1}"
if [ -z $signal ]; then
    usage
fi

case "${signal}" in
    -p|-P|--poweroff|-h|-H|--halt)
        signal="SIGQUIT"
        ;;
    -r|-R|--reboot)
        signal="SIGINT"
        ;;
    #-h|-H|--halt)
        #       signal="SIGUSR2"
        #       ;;
    *)
       usage
esac

exec "${scandir}"/service/.s6-svscan/"${signal}"
