#! /bin/sh

s6-echo "[     Shutdown   ]     : Saving sytem clock to rtc0" 
. /etc/s6/s6.conf

if [[ ${HARDWARECLOCK} = UTC || ${HARDWARECLOCK} = utc ]] ; then
    HWC=$(echo $HARDWARECLOCK | tr A-Z a-z)
    hwclock  --systohc --$HWC
else
    # If HARDWARECLOCK is anything else, commented, or null, then use 'localtime' as the default...
    HWC=localtime
    hwclock --systohc --$HWC
fi
