#!/bin/sh -e

### This script is called once at boot time by rc.init, and is
### also called by the runleveld service every time the user
### requests a machine state change via telinit.
### Ideally, it should just be a call to the service manager.

test "$#" -gt 0 || { echo 'runlevel: fatal: too few arguments' 1>&2 ; exit 100 ; }

### Services are managed by s6-rc:
### "-v0" -- silence all warnings
### "-v1" -- warnings & errors will be printed to stderr
### "-v2" -- write info messages whenever s6-rc performs a transition
### "-v3" -- 3 3+, debug info

exec s6-rc -v1 -up change "$1"
