#!/bin/sh

echo "\n[ >>>> ] Stopping networking interfaces...\n"
# This will stop and bring down the network interfaces.
for file in  /etc/sysconfig/ifconfig.*
do
   net_files="${file} ${net_files}"
done
for file in ${net_files}
do
   interface=${file##*/ifconfig.}
   # Skip if $file is * (because nothing was found)
   if [ "${interface}" = "*" ]
   then
            continue
   fi
   /sbin/ifdown ${interface}
   echo "[ ok ] ${interface} is down\n"
done
