#! /bin/sh

s6-echo "[ Read-Only Mode ] 5/9 : Setting up Kernel Static Node(s)" >> /run/bootserv.log
 
if [ ! -d "/run/tmpfiles.d" ]
then
	 mkdir /run/tmpfiles.d
fi

kmod static-nodes --format=tmpfiles --output=/run/tmpfiles.d/kmod.conf
